name: Build Zig Use

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          # Linux targets
          - x86-linux
          - x86_64-linux
          - aarch64-linux
          - riscv64-linux
          # macOS targets
          - x86_64-macos
          - aarch64-macos

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Zig
        uses: mlugg/setup-zig@v2.0.1

      - name: Build for ${{ matrix.target }}
        run: |
          zig build -Dtarget=${{ matrix.target }} --release=safe
